language: python

branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
      - samtools

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - pip install -U tox-travis pip setuptools wheel

script:
  - tox
