language: python
python:
  - "2.7"
  - "3.4"
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-h5py python-numexpr cython python3-numpy python3-scipy python3-h5py python3-numexpr cython3
install:
  - pip install -r requirements.txt
  - pip install flake8
  - python setup.py install
script:
  - nosetests -v --with-doctest allel
  - flake8 allel
