language: python

branches:
  only:
    - master

dist: trusty
sudo: required

#addons:
#  apt:
#    packages:
#      - tabix

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - sudo apt-get install tabix
  - pip install -U tox-travis pip setuptools wheel

script:
  - tox
